---
title: "Lab 06 - Conveying the right message through visualisation"
author: [Ronan & Tony]
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```


### Exercise 1

```{r create-data}
df <- tribble(
  ~date, ~count, ~status,
  "7,13,20", 22.9, "mask",
  "7,14,20", 19.5,"mask",
  "7,15,20", 19.9,"mask",
  "7,16,20", 20,"mask",
  "7,17,20", 19.6,"mask",
  "7,18,20", 20,"mask",
  "7,19,20", 20,"mask",
  "7,21,20", 21,"mask",
  "7,22,20", 20.7,"mask",
  "7,23,20", 19.9,"mask",
  "7,24,20", 20.1,"mask",
  "7,25,20", 20,"mask",
  "7,26,20", 19.5,"mask",
  "7,27,20", 18.3,"mask",
  "7,28,20", 16.7,"mask",
  "7,29,20", 16.4,"mask",
  "7,30,20", 16.8,"mask",
  "7,31,20", 16.2,"mask",
  "8,1,20", 16.1,"mask",
  "8,2,20", 16,"mask",
  "8,3,20", 16,"mask",
   "7,13,20", 20.5, "no mask",
  "7,14,20", 20.3,"no mask",
  "7,15,20", 20.6,"no mask",
  "7,16,20", 20.9,"no mask",
  "7,17,20", 20.8,"no mask",
  "7,18,20", 20.6,"no mask",
  "7,19,20", 20.1,"no mask",
  "7,21,20", 19.6,"no mask",
  "7,22,20", 19.7,"no mask",
  "7,23,20", 19.4,"no mask",
  "7,24,20", 20,"no mask",
  "7,25,20", 19.9,"no mask",
  "7,26,20", 21,"no mask",
  "7,27,20", 20.8,"no mask",
  "7,28,20", 20.7,"no mask",
  "7,29,20", 20.6,"no mask",
  "7,30,20", 20.9,"no mask",
  "7,31,20", 20.4,"no mask",
  "8,1,20", 19.9,"no mask",
  "8,2,20", 20,"no mask",
  "8,3,20", 20,"no mask",
  
)

df
```


### Exercise 2

```{r better-viz}
# add code here
```


### Exercise 3

*Add your narrative here.*


### Exercise 4

*Add your narrative here.*
